version: '3'

services:
    node:
        container_name: sdctimetracker
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        labels:
            - "traefik.enable=true"
            - "traefik.basic.fronten.rule=Host:sdctimetracker.verns.space"
            - "traefik.backend=nodetimetracker"
            - "traefik.frontend.rule=Host:sdctimetracker.verns.space"
            - "traefik.docker.network=proxy"
            - "traefik.port=8082"
        working_dir: /home/node/app
        user: node
        expose:
            - "8082"
        networks:
            - "proxy"
        volumes:
            - ./:/home/node/app
        entrypoint: ./docker/entry.sh
networks:
    proxy:
        external: true
